# Generated by Django 3.1.14 on 2022-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Body',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
